//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Userphoto
    {
        public int id_photo { get; set; }
        public int id_user { get; set; }
        public byte[] photoBinary { get; set; }
        public string photoPath { get; set; }
    
        public virtual T_Users T_Users { get; set; }
    }
}
